In [141]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [142]:
from sklearn import preprocessing

In [143]:
veriler = pd.read_csv("tenis.csv")

In [144]:
veriler

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

In [145]:
outlook = veriler.iloc[:,0]

In [146]:
outlook

0        sunny
1        sunny
2     overcast
3        rainy
4        rainy
5        rainy
6     overcast
7        sunny
8        sunny
9        rainy
10       sunny
11    overcast
12    overcast
13       rainy
Name: outlook, dtype: object

In [147]:
play = veriler.iloc[:,4]
windy = veriler.iloc[:,3]

In [148]:
play

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: play, dtype: object

In [149]:
le = preprocessing.LabelEncoder()
ohe = preprocessing.OneHotEncoder()

In [150]:
play = le.fit_transform(veriler.iloc[:,-1:])
windy = le.fit_transform(veriler.iloc[:,3])
outlook = le.fit_transform(veriler.iloc[:,0])

C:\Users\Taha\venv\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [151]:
play

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [152]:
windy

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1], dtype=int64)

In [153]:
outlook

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [154]:
veriler2 = veriler.apply(le.fit_transform)

In [155]:
veriler2

outlook  temperature  humidity  windy  play
0         2           11         4      0     0
1         2            8         6      1     0
2         0           10         5      0     1
3         1            4         9      0     1
4         1            2         3      0     1
5         1            1         1      1     0
6         0            0         0      1     1
7         2            6         8      0     0
8         2            3         1      0     1
9         1            7         3      0     1
10        2            7         1      1     1
11        0            6         6      1     1
12        0            9         2      0     1
13        1            5         7      1     0

In [156]:
c = veriler2.iloc[:,:1]

In [157]:
c

outlook
0         2
1         2
2         0
3         1
4         1
5         1
6         0
7         2
8         2
9         1
10        2
11        0
12        0
13        1

In [158]:
c = ohe.fit_transform(c).toarray()

In [159]:
c

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [160]:
outlook2 = pd.DataFrame(data=c, index = range(14) , columns = ['overcast', 'sunny', 'rainy'])


In [161]:
sonveriler = pd.concat([veriler2.iloc[:,3:], outlook2, veriler.iloc[:,1:3]], axis = 1)

In [162]:
sonveriler

windy  play  overcast  sunny  rainy  temperature  humidity
0       0     0       0.0    0.0    1.0           85        85
1       1     0       0.0    0.0    1.0           80        90
2       0     1       1.0    0.0    0.0           83        86
3       0     1       0.0    1.0    0.0           70        96
4       0     1       0.0    1.0    0.0           68        80
5       1     0       0.0    1.0    0.0           65        70
6       1     1       1.0    0.0    0.0           64        65
7       0     0       0.0    0.0    1.0           72        95
8       0     1       0.0    0.0    1.0           69        70
9       0     1       0.0    1.0    0.0           75        80
10      1     1       0.0    0.0    1.0           75        70
11      1     1       1.0    0.0    0.0           72        90
12      0     1       1.0    0.0    0.0           81        75
13      1     0       0.0    1.0    0.0           71        91

In [163]:
from sklearn.model_selection import train_test_split

In [164]:
x_train, x_test, y_train, y_test = train_test_split(sonveriler.iloc[:,:-1], sonveriler.iloc[:,-1:], test_size=0.33, random_state=0)

In [165]:
x_train

windy  play  overcast  sunny  rainy  temperature
13      1     0       0.0    1.0    0.0           71
9       0     1       0.0    1.0    0.0           75
1       1     0       0.0    0.0    1.0           80
7       0     0       0.0    0.0    1.0           72
10      1     1       0.0    0.0    1.0           75
3       0     1       0.0    1.0    0.0           70
0       0     0       0.0    0.0    1.0           85
5       1     0       0.0    1.0    0.0           65
12      0     1       1.0    0.0    0.0           81

In [166]:
y_train

humidity
13        91
9         80
1         90
7         95
10        70
3         96
0         85
5         70
12        75

In [167]:
x_test

windy  play  overcast  sunny  rainy  temperature
8       0     1       0.0    0.0    1.0           69
6       1     1       1.0    0.0    0.0           64
4       0     1       0.0    1.0    0.0           68
11      1     1       1.0    0.0    0.0           72
2       0     1       1.0    0.0    0.0           83

In [168]:
y_test

humidity
8         70
6         65
4         80
11        90
2         86

In [169]:
from sklearn.linear_model import LinearRegression

In [170]:
regressor = LinearRegression()

In [171]:
regressor.fit(x_train, y_train)

LinearRegression()

In [172]:
y_pred = regressor.predict(x_test)

In [173]:
y_pred

array([[84.45365573],
       [63.93839954],
       [85.76050662],
       [64.21013241],
       [75.06793322]])

In [174]:
import statsmodels.api as sm


In [175]:
sonveriler

windy  play  overcast  sunny  rainy  temperature  humidity
0       0     0       0.0    0.0    1.0           85        85
1       1     0       0.0    0.0    1.0           80        90
2       0     1       1.0    0.0    0.0           83        86
3       0     1       0.0    1.0    0.0           70        96
4       0     1       0.0    1.0    0.0           68        80
5       1     0       0.0    1.0    0.0           65        70
6       1     1       1.0    0.0    0.0           64        65
7       0     0       0.0    0.0    1.0           72        95
8       0     1       0.0    0.0    1.0           69        70
9       0     1       0.0    1.0    0.0           75        80
10      1     1       0.0    0.0    1.0           75        70
11      1     1       1.0    0.0    0.0           72        90
12      0     1       1.0    0.0    0.0           81        75
13      1     0       0.0    1.0    0.0           71        91

In [176]:
X = np.append(arr = np.ones((14,1)).astype(int), values = sonveriler.iloc[:,:-1], axis = 1)

In [177]:
X

array([[ 1.,  0.,  0.,  0.,  0.,  1., 85.],
       [ 1.,  1.,  0.,  0.,  0.,  1., 80.],
       [ 1.,  0.,  1.,  1.,  0.,  0., 83.],
       [ 1.,  0.,  1.,  0.,  1.,  0., 70.],
       [ 1.,  0.,  1.,  0.,  1.,  0., 68.],
       [ 1.,  1.,  0.,  0.,  1.,  0., 65.],
       [ 1.,  1.,  1.,  1.,  0.,  0., 64.],
       [ 1.,  0.,  0.,  0.,  0.,  1., 72.],
       [ 1.,  0.,  1.,  0.,  0.,  1., 69.],
       [ 1.,  0.,  1.,  0.,  1.,  0., 75.],
       [ 1.,  1.,  1.,  0.,  0.,  1., 75.],
       [ 1.,  1.,  1.,  1.,  0.,  0., 72.],
       [ 1.,  0.,  1.,  1.,  0.,  0., 81.],
       [ 1.,  1.,  0.,  0.,  1.,  0., 71.]])

In [178]:
X_l = sonveriler.iloc[:,[0,1,2,3,4,5]].values

In [179]:
X_l = np.array(X_l, dtype = float)

In [180]:
X_l

array([[ 0.,  0.,  0.,  0.,  1., 85.],
       [ 1.,  0.,  0.,  0.,  1., 80.],
       [ 0.,  1.,  1.,  0.,  0., 83.],
       [ 0.,  1.,  0.,  1.,  0., 70.],
       [ 0.,  1.,  0.,  1.,  0., 68.],
       [ 1.,  0.,  0.,  1.,  0., 65.],
       [ 1.,  1.,  1.,  0.,  0., 64.],
       [ 0.,  0.,  0.,  0.,  1., 72.],
       [ 0.,  1.,  0.,  0.,  1., 69.],
       [ 0.,  1.,  0.,  1.,  0., 75.],
       [ 1.,  1.,  0.,  0.,  1., 75.],
       [ 1.,  1.,  1.,  0.,  0., 72.],
       [ 0.,  1.,  1.,  0.,  0., 81.],
       [ 1.,  0.,  0.,  1.,  0., 71.]])

In [181]:
model = sm.OLS(sonveriler.iloc[:,-1:],X_l).fit()

In [182]:
model.summary()

C:\Users\Taha\venv\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Sun, 04 Sep 2022   Prob (F-statistic):              0.661
Time:                        15:40:30   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.593     -20.698      12.641
x2            -8.2778      8.029     -1.031      0.333     -26.793      10.237
x3            52.3891     50.214      1.043      0.327     -63.404     168.183
x4            55.6337     45.233      1.230      0.254     -48.673     159.940
x5            49.4291     48.337      1.023      0.336     -62.035     160.893
x6             0.4920      0.597      0.825      0.433      -0.884       1.868
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   2.416
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.823
Skew:                           0.389   Prob(JB):                        0.663
Kurtosis:                       2.103   Cond. No.                     2.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [183]:
sonveriler = sonveriler.iloc[:,1:]
sonveriler

play  overcast  sunny  rainy  temperature  humidity
0      0       0.0    0.0    1.0           85        85
1      0       0.0    0.0    1.0           80        90
2      1       1.0    0.0    0.0           83        86
3      1       0.0    1.0    0.0           70        96
4      1       0.0    1.0    0.0           68        80
5      0       0.0    1.0    0.0           65        70
6      1       1.0    0.0    0.0           64        65
7      0       0.0    0.0    1.0           72        95
8      1       0.0    0.0    1.0           69        70
9      1       0.0    1.0    0.0           75        80
10     1       0.0    0.0    1.0           75        70
11     1       1.0    0.0    0.0           72        90
12     1       1.0    0.0    0.0           81        75
13     0       0.0    1.0    0.0           71        91

In [185]:
X = np.append(arr = np.ones((14,1)).astype(int), values = sonveriler.iloc[:,:-1], axis = 1)
X_l = sonveriler.iloc[:,[0,1,2,3,4]].values
X_l = np.array(X_l, dtype = float)
model = sm.OLS(sonveriler.iloc[:,-1:],X_l).fit()
model.summary()

C:\Users\Taha\venv\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Sun, 04 Sep 2022   Prob (F-statistic):              0.546
Time:                        15:41:30   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.2865      6.909     -0.910      0.387     -21.916       9.343
x2            36.6564     39.905      0.919      0.382     -53.615     126.927
x3            41.9135     36.464      1.149      0.280     -40.573     124.400
x4            35.1064     39.339      0.892      0.395     -53.884     124.097
x5             0.6484      0.506      1.282      0.232      -0.496       1.793
==============================================================================
Omnibus:                        0.887   Durbin-Watson:                   2.360
Prob(Omnibus):                  0.642   Jarque-Bera (JB):                0.810
Skew:                           0.424   Prob(JB):                        0.667
Kurtosis:                       2.181   Cond. No.                     1.73e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [186]:
x_train = x_train.iloc[:,1:]

In [187]:
x_test = x_test.iloc[:,1:]

In [189]:
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)
y_pred

array([[77.98135142],
       [68.29304916],
       [81.05037539],
       [71.44926132],
       [75.78905304]])

In [190]:
y_test

humidity
8         70
6         65
4         80
11        90
2         86